AI_TIPS_IDEAS = [
    "Zero-Shot vs Few-Shot Prompting",
    "Giving AI the Right Context",
    "Using Custom Instructions and System Prompts",
    "AI for Accessibility (Screen Readers & Captions)",
    "AI for Kids' Homework Help",
    "AI for Elderly and First-Time Users",
    "AI for Sleep and Relaxation",
    "AI for Cooking and Recipes",
    "AI for Home Repairs and DIY Projects",
    "AI for Gardening",
    "AI for Pet Care",
    "AI for Car Maintenance",
    "AI for Smarter Shopping",
    "AI for Taxes and Insurance Basics",
    "AI for Understanding Legal Documents",
    "AI for Freelancers and Side Hustles",
    "AI for Online Sellers and E-commerce",
    "AI for No-Code App Building",
    "AI for Spreadsheets and Data Analysis",
    "AI for APIs and Automation Basics",
    "AI for Debugging Like a Developer",
    "AI for Writing Technical Documentation",
    "AI for Cybersecurity Awareness",
    "Understanding AI Hallucinations",
    "AI Bias and Fairness Explained",
    "AI for Personal Website Building",
    "AI for Podcast and Video Scripting",
    "AI for Time Management",
    "AI for Note-Taking and Second Brain Systems",
    "AI Tokens and Context Windows Explained",
]

AI_PROMPTS_IDEAS = [
    "Grocery List and Meal Prep Planning",
    "Household Budget Spreadsheet Creation",
    "Car Buying Research and Comparison",
    "Home Renovation Planning",
    "Insurance Policy Comparison",
    "Tax Filing Checklist",
    "Rental Agreement Review (Plain English)",
    "Job Description Writing",
    "Employee Onboarding Documents",
    "Performance Review Writing",
    "Team Standup Notes",
    "Code Review Assistant",
    "API Documentation Writing",
    "SQL Query Generation",
    "Regex Pattern Creation",
    "Excel Formula Generation",
    "Data Cleaning and Formatting",
    "Chatbot Script Design",
    "Landing Page Copywriting",
    "App Feature Brainstorming",
    "Startup Pitch Deck Outline",
    "Customer Persona Creation",
    "Survey Question Design",
    "Event Planning Checklist",
    "Wedding Speech Writing",
    "Kids' Bedtime Story Creation",
    "Birthday Party Planning",
    "Gift Idea Suggestions",
    "Personal Statement for Grad School Applications",
    "Debate and Argument Preparation",
]