AI_TIPS_IDEAS = [
    "Be Specific",
    "Role Prompting",
    "Few-Shot Examples",
    "Step-by-Step Thinking",
    "Define Output Format",
    "Ask Follow-Up Questions",
    "AI for Productivity",
    "AI for Research",
    "AI for Writing",
    "AI for Email Writing",
    "AI for Meeting Summaries",
    "AI for Content Creation",
    "AI for Business Ideas",
    "AI for Marketing",
    "AI for Resume Building",
    "AI for Job Interviews",
    "AI for Learning",
    "AI for Coding",
    "AI Agents for Work",
    "When AI Lies to You",
    "AI for Health and Fitness",
    "AI for Travel Planning",
    "AI for Money and Finance",
    "AI for Social Media Growth",
    "When NOT to Use AI",
    "Talking to AI Like a Pro",
    "AI for Image Creation",
    "AI for Video Editing",
]

AI_PROMPTS_IDEAS = [
    "LinkedIn Post Generation",
    "Instagram Caption Creation",
    "Blog Writing",
    "YouTube Script Creation",
    "Resume Improvement",
    "Cover Letter Writing",
    "Interview Preparation",
    "Email Writing",
    "Sales Outreach",
    "Business Idea Validation",
    "Market Research",
    "Competitor Analysis",
    "Marketing Campaign Ideas",
    "Customer Support Replies",
    "Meeting Summary",
    "Presentation Creation",
    "Coding Assistant",
    "Debugging Code",
    "Learning New Skills",
    "Study Notes Creation",
    "AI Agent Design",
    "Personal Brand Building",
    "Negotiating a Salary Raise",
    "Writing a Cold DM or Email",
    "Planning a Trip with AI",
    "Making a Decision Faster",
    "Creating a Study Plan",
    "Getting Feedback on Your Work",
    "Turning an Idea Into a Business",
]